In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.0
2.4.1

In [2]:
events = pd.read_csv(
    r"C:\Users\Jesus\Desktop\Formación\Data Analytics\Proyecto final\DataSet1\events.csv",
    low_memory=False
)

In [3]:
events.shape

(941009, 22)

In [4]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 941009 entries, 0 to 941008
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_odsp        941009 non-null  str
 1   id_event       941009 non-null  str
 2   sort_order     941009 non-null  int64
 3   time           941009 non-null  int64
 4   text           941009 non-null  str
 5   event_type     941009 non-null  int64
 6   event_type2    214293 non-null  float64
 7   side           941009 non-null  int64
 8   event_team     941009 non-null  str
 9   opponent       941009 non-null  str
 10  player         880009 non-null  str
 11  player2        291310 non-null  str
 12  player_in      51715 non-null   str
 13  player_out     51738 non-null   str
 14  shot_place     227459 non-null  float64
 15  shot_outcome   228498 non-null  float64
 16  is_goal        941009 non-null  int64
 17  location       467067 non-null  float64
 18  bodypart       229185 non-null  float64
 19  assist_method  941009 non-null  int64
 20  situation      229137 non-null  float64
 21  fast_break     941009 non-null  int64
dtypes: float64(6), int64(7), str(9)
memory usage: 157.9 MB

In [5]:
events.head(10)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
5,UFot0hit/,UFot0hit6,6,9,Hand ball by Jose Paolo Guerrero (Hamburg).,10,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
6,UFot0hit/,UFot0hit7,7,10,"Corner, Hamburg. Conceded by Lukasz Piszczek.",2,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
7,UFot0hit/,UFot0hit8,8,11,Chris Lowe (Borussia Dortmund) wins a free kic...,8,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
8,UFot0hit/,UFot0hit9,9,11,Foul by Gojko Kacar (Hamburg).,3,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
9,UFot0hit/,UFot0hit10,10,13,Foul by Gokhan Tore (Hamburg).,3,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [6]:
events["event_type"].value_counts().sort_index()

event_type
1     229135
2      91204
3     232925
4      39911
5        100
6       1152
7      51738
8     237932
9      43476
10     10730
11      2706
Name: count, dtype: int64

In [7]:
event_type_map = {
    1: "shot",
    2: "corner",
    3: "foul",
    4: "yellow_card",
    5: "second_yellow",
    6: "red_card",
    7: "substitution",
    8: "pass",
    9: "free_kick",
    10: "offside",
    11: "handball"
}

events["event_type_name"] = events["event_type"].map(event_type_map)

events["event_type_name"].value_counts()

event_type_name
pass             237932
foul             232925
shot             229135
corner            91204
substitution      51738
free_kick         43476
yellow_card       39911
offside           10730
handball           2706
red_card           1152
second_yellow       100
Name: count, dtype: int64

In [8]:
key_events = events[
    events["event_type"].isin([1, 3, 4, 5, 6, 8])
].copy()

key_events["event_type_name"].value_counts()

event_type_name
pass             237932
foul             232925
shot             229135
yellow_card       39911
red_card           1152
second_yellow       100
Name: count, dtype: int64

In [9]:
player_event_counts = (
    key_events
    .groupby(["player", "event_type_name"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

player_event_counts.head()

event_type_name,player,foul,pass,red_card,second_yellow,shot,yellow_card
0,aaron,32,51,0,0,48,11
1,aaron cresswell,38,69,0,1,52,8
2,aaron hughes,2,6,0,0,1,2
3,aaron hunt,95,212,1,0,215,9
4,aaron lennon,38,63,0,0,57,5

In [10]:
player_event_counts["total_cards"] = (
    player_event_counts["yellow_card"] +
    player_event_counts["second_yellow"] +
    player_event_counts["red_card"]
)

player_event_counts["cards_per_foul"] = (
    player_event_counts["total_cards"] /
    player_event_counts["foul"]
)

player_event_counts.head()

event_type_name,player,foul,pass,red_card,second_yellow,shot,yellow_card,total_cards,cards_per_foul
0,aaron,32,51,0,0,48,11,11,0.343750
1,aaron cresswell,38,69,0,1,52,8,9,0.236842
2,aaron hughes,2,6,0,0,1,2,2,1.000000
3,aaron hunt,95,212,1,0,215,9,10,0.105263
4,aaron lennon,38,63,0,0,57,5,5,0.131579

In [11]:
player_event_counts["cards_per_foul"] = (
    player_event_counts["cards_per_foul"]
    .replace([np.inf, -np.inf], np.nan)
)

In [12]:
player_match_events = (
    key_events
    .groupby(["id_odsp", "player", "event_team", "opponent", "event_type_name"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

player_match_events.head()

event_type_name,id_odsp,player,event_team,opponent,foul,pass,red_card,second_yellow,shot,yellow_card
0,004f4ING/,bafetimbi gomis,Swansea,Southampton,1,4,0,0,2,0
1,004f4ING/,dusan tadic,Southampton,Swansea,0,2,0,0,1,0
2,004f4ING/,eljero elia,Southampton,Swansea,4,1,0,0,0,0
3,004f4ING/,federico fernandez,Swansea,Southampton,0,0,0,0,1,0
4,004f4ING/,graziano pelle,Southampton,Swansea,0,1,0,0,2,0

In [13]:
player_match_events["total_cards"] = (
    player_match_events.get("yellow_card", 0) +
    player_match_events.get("second_yellow", 0) +
    player_match_events.get("red_card", 0)
)

In [14]:
player_match_events = player_match_events.fillna(0)


player_match_events.to_csv(
    "C:\\Users\\Jesus\\Desktop\\Formación\\Data Analytics\\Proyecto final\\player_match_events.csv",
    index=False
)